### ISSUE TITLE
4.0.0: Disconnecting from cast session throws unhandled promise rejection error [Android]

### ISSUE THREAD

**Issue by maliotti** [react-native-google-cast/react-native-google-cast#266]
On Android only, ending the cast session throws an unhandled promise rejection error. This happens either by calling `sessionManager.endCurrentSession()` or by disconnecting manually by clicking the cast icon and then clicking "Stop casting" in the popup dialogue.)

Looks like this might be related to #251 ?

Version: `react-native-google-cast` version `4.0.0`
Platform: Android

To reproduce:
- On Android, start casting content
- Then disconnect the cast (you can do it programmatically as well)
- Notice that the following error will be logged to the console: `Unhandled promise rejection [Error: No castSession!]`

![Screenshot_20210108-152944](https://user-images.githubusercontent.com/5532759/104076864-40f66580-51cc-11eb-8fdf-24dcde4d224b.png)

**Comment by urvashichhabra** [comment]
Any fixes ?

**Comment by tombotley** [comment]
I'm also seeing this in version 4.0.3

**Comment by petrbela** [comment]
Yeah, this is still outstanding, I'll try to get to it asap.

**Comment by petrbela** [comment]
This should be fixed in the latest version.

**Comment by jeffmon** [comment]
I'm still getting this error on the latest version `4.2.4`, on Android. It happens when I tap "Stop Casting" on the device.
